# This script is an edited version of the example found at
# https://git.ligo.org/lscsoft/example-ci-project/blob/python/.gitlab-ci.yml
# Each 0th-indendation level is a job that will be run within GitLab CI
# The only exception are a short list of reserved keywords
#
# https://docs.gitlab.com/ee/ci/yaml/#gitlab-ci-yml

# stages is a reserved keyword that defines job dependencies and
# parallelization. each stage runs in parallel but must complete
# before the next stage begins

stages:
  - test
  - deploy

# test example on Debian 8 "jessie"
exitcode-jessie:
  stage: test
  image: ligo/software:jessie
  script:
    - pip install -r requirements.txt
    - pip install coverage
    - pip install coverage-badge
    - python setup.py install
    - for test in test/*.py; do coverage run $test; done
#    - coverage run test/parameter_tests.py
#    - coverage run test/tests.py
#    - coverage run test/waveform_generator_tests.py
    - coverage html --include=peyote/*
    - coverage-badge -o coverage.svg
  artifacts:
    paths:
      - htmlcov/
      - coverage.svg

pages:
  stage: deploy
  dependencies:
    - exitcode-jessie
  script:
    - mv htmlcov/ public/
    - mv coverage.svg public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  #only:
    #- master
